# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongo_geo 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "mongo_geo"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Michael Parrish"]
  s.date = "2014-04-04"
  s.description = "A MongoMapper plugin that adds geospatial functionality."
  s.email = "mtparrish@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/mongo_geo.rb",
    "mongo_geo.gemspec",
    "test/helper.rb",
    "test/test_mongo_geo.rb",
    "test/test_plucky_extensions.rb"
  ]
  s.homepage = "http://github.com/parrish/mongo_geo"
  s.rubygems_version = "2.2.2"
  s.summary = "A MongoMapper plugin that adds geospatial functionality."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.9.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<mongo_mapper>, [">= 0.9.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<mongo_mapper>, [">= 0.9.0"])
  end
end

